strictness: high
output-format: pylint

ignore-paths:
  - ^docs?/
  - ^tests?/?
  - /tests?(/|$)
  - .*/tests(/|$)
  - (^|/)test_[_a-zA-Z0-9]+.py$
  - (^|/)[_a-zA-Z0-9]+_tests?.py$
  - (^|/)tests?.py
  - ^setup.py$
  - (^|/)\..+

pylint:
  disable:
    - wrong-import-order
    - no-self-argument
    - empty-docstring
    - no-self-use
    - unused-format-string-key
    - multiple-statements
    - broad-except
    - superfluous-parens
    - no-member
    - no-name-in-module
    - global-statement
    - too-many-return-statements
    - relative-import
    - wildcard-import
    - pointless-except
    - missing-docstring
    - bad-builtin
    - invalid-name
    - missing-function-docstring
    - missing-class-docstring
    - missing-module-docstring
  enable:
    - fixme  # ✅ Enable detection of TODO and FIXME
  options:
    max-line-length: 159

pycodestyle:
  disable:
    - E123
    - E121
    - E302
  enable: []

pyflakes:
  enable: []
  disable:
    - F403

mccabe:
  options:
    max-complexity: 15

dodgy:
  run: true

bandit:
  run: true
