output-format: pylint

tools:
  pylint:
    disable:
      - C0114  # Disable missing module docstring warning
    enable:
      - W0511  # ✅ Explicitly enables TODO/FIXME detection
    notes:
      - TODO
      - FIXME

strictness: none  # ✅ Disables strict filtering, so TODO/FIXME aren't ignored





