output-format: pylint

tools:
  pylint:
    enable:
      - W0511  # ✅ Enables TODO/FIXME detection
    notes:
      - TODO
      - FIXME

strictness: veryhigh # ✅ Prevents filtering out warnings





